query allWebsites {
  websites {
    id
    url
    targetAmount
    monthlyRevenue
    monthlyProfit
    smallDescription
    detailDescription
    thumbnail {
      url
    }
    investments {
      amountInvested
      user {
        id
      }
    }
  }
}
