query detailWebsite($id: ID!) {
  website(id: $id) {
    id
    url
    targetAmount
    monthlyRevenue
    monthlyProfit
    smallDescription
    detailDescription
    thumbnail {
      url
    }
    createdAt
    investments {
      id
      amountInvested
      user {
        username
        id
      }
    }
  }
}
