query detailWebsite($id: ID!) {
  website(id: $id) {
    id
    url
    targetAmount
    monthlyRevenue
    monthlyProfit
    smallDescription
    detailDescription
    investments {
      id
      amountInvested
    }
  }
}
