query allWebsites {
  websites {
    id
    url
    thumbnail {
      url
    }
    shortDescription
    targetAmount
    progressAmount
    monthlyProfit
    yearlyProfit
    numberOfInvestors
    description {
      html
    }
  }
}
